### ISSUE TITLE
Use --unstable-ffi flag when working with the library.

### ISSUE THREAD

**Issue by iyifr** [denosaurs/netsaur#70]
It's not explicitly stated anywhere in the docs that the library will refuse to run without the `--unstable-ffi` flag. 

i.e `deno run --unstable-ffi` main.ts (file with your model code in it)

You will encounter this error without the flag. 

![image](https://github.com/user-attachments/assets/4a9774d6-da8b-427b-bf38-a8561a98ed2d)

**Comment by retraigo** [comment]
dlopen isn't unstable in Deno 2 afaik.

Also you don't need to use `--unstable-ffi` even before Deno 2 if you use the WASM backend.

**Comment by iyifr** [comment]
Oh okay! I'm not on deno2 yet, might upgrade later. 

I'm using the CPU backend, and i'm pretty sure other first timers will also use it. 

It could be added in the docs.

Also where's the src for the docs?

**Comment by retraigo** [comment]
Sounds good. We'll add a note mentioning how Deno 1.xx requires `--unstable` or `--unstable-ffi` to use the CPU backend.

As for the docs, if you are talking about [netsaur.deno.dev](https://netsaur.deno.dev), it is not open source at the moment (since it's WIP) but will be in the near future.

**Comment by iyifr** [comment]
Okay 👍🏾 👌🏽
